In [4]:
from __future__ import division, print_function
import torch

### Tensors 
Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [5]:
# construct a 5x3 matrix
x = torch.empty(5,3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -1.5552e-33,  4.5745e-41],
        [-1.5818e-33,  4.5745e-41,  2.0979e-17],
        [ 4.5745e-41, -7.6619e-34,  4.5745e-41],
        [ 6.4113e-37,  1.4013e-45,  0.0000e+00]])


In [6]:
#construct a random initialized matrix
x = torch.rand(5,3)
print(x)

tensor([[0.6171, 0.0967, 0.9533],
        [0.4334, 0.1794, 0.3015],
        [0.7694, 0.0502, 0.2487],
        [0.2343, 0.4571, 0.2086],
        [0.3765, 0.2114, 0.0394]])


In [7]:
#construct a matrix filled with zeros of dtype long.
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
#construct a maxtrix directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
#or create a tensor based on an existing tensor.
#These methods will reuse properties of the input tensor, e.g. dtype,
#unless new values are provided by user
x = x.new_ones(5,3,dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.7649, -1.5699,  0.8210],
        [ 1.9056,  0.7677, -0.0955],
        [ 0.3712,  1.3719,  0.1430],
        [-0.0170, -0.8239,  0.6006],
        [ 0.7158, -0.5081, -0.7656]])


In [10]:
#torch.Size is in fact a tuple, so it supports all tuple operations.
print(x.size())

torch.Size([5, 3])


### Operations
There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.

In [11]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 2.7011, -1.4604,  1.6458],
        [ 2.6774,  0.7942,  0.1962],
        [ 0.6707,  2.1905,  0.1949],
        [ 0.0732, -0.1005,  1.3082],
        [ 0.9648, -0.1340, -0.3946]])


In [12]:
print(torch.add(x,y))

tensor([[ 2.7011, -1.4604,  1.6458],
        [ 2.6774,  0.7942,  0.1962],
        [ 0.6707,  2.1905,  0.1949],
        [ 0.0732, -0.1005,  1.3082],
        [ 0.9648, -0.1340, -0.3946]])


In [13]:
res = torch.empty(5,3)
torch.add(x,y, out=res)
print(res)

tensor([[ 2.7011, -1.4604,  1.6458],
        [ 2.6774,  0.7942,  0.1962],
        [ 0.6707,  2.1905,  0.1949],
        [ 0.0732, -0.1005,  1.3082],
        [ 0.9648, -0.1340, -0.3946]])


In [14]:
y.add_(x)
print(y)

tensor([[ 2.7011, -1.4604,  1.6458],
        [ 2.6774,  0.7942,  0.1962],
        [ 0.6707,  2.1905,  0.1949],
        [ 0.0732, -0.1005,  1.3082],
        [ 0.9648, -0.1340, -0.3946]])


#### Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [15]:
print(x[:,1])

tensor([-1.5699,  0.7677,  1.3719, -0.8239, -0.5081])


In [16]:
# resize
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
#If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0456])
1.04564535618


### Numpy & Pytorch tensor bridge
Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.

In [18]:
#tensor to numpy array
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [19]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [20]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [21]:
# numpy to tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [22]:
# will not change a. c will be a brightly new tensor 
c = torch.tensor(a)

In [25]:
c.add_(1);a

array([2., 2., 2., 2., 2.])